package com.yaoyao.yiuse.dbmanager.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yaoyao.yiuse.dbmanager.entity.AimsEntity;
import com.yaoyao.yiuse.dbmanager.entity.ResourcesEntity;
import com.yaoyao.yiuse.dbmanager.entity.ResTagEntity;

import com.yaoyao.yiuse.dbmanager.dao.AimsEntityDao;
import com.yaoyao.yiuse.dbmanager.dao.ResourcesEntityDao;
import com.yaoyao.yiuse.dbmanager.dao.ResTagEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aimsEntityDaoConfig;
    private final DaoConfig resourcesEntityDaoConfig;
    private final DaoConfig resTagEntityDaoConfig;

    private final AimsEntityDao aimsEntityDao;
    private final ResourcesEntityDao resourcesEntityDao;
    private final ResTagEntityDao resTagEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aimsEntityDaoConfig = daoConfigMap.get(AimsEntityDao.class).clone();
        aimsEntityDaoConfig.initIdentityScope(type);

        resourcesEntityDaoConfig = daoConfigMap.get(ResourcesEntityDao.class).clone();
        resourcesEntityDaoConfig.initIdentityScope(type);

        resTagEntityDaoConfig = daoConfigMap.get(ResTagEntityDao.class).clone();
        resTagEntityDaoConfig.initIdentityScope(type);

        aimsEntityDao = new AimsEntityDao(aimsEntityDaoConfig, this);
        resourcesEntityDao = new ResourcesEntityDao(resourcesEntityDaoConfig, this);
        resTagEntityDao = new ResTagEntityDao(resTagEntityDaoConfig, this);

        registerDao(AimsEntity.class, aimsEntityDao);
        registerDao(ResourcesEntity.class, resourcesEntityDao);
        registerDao(ResTagEntity.class, resTagEntityDao);
    }
    
    public void clear() {
        aimsEntityDaoConfig.clearIdentityScope();
        resourcesEntityDaoConfig.clearIdentityScope();
        resTagEntityDaoConfig.clearIdentityScope();
    }

    public AimsEntityDao getAimsEntityDao() {
        return aimsEntityDao;
    }

    public ResourcesEntityDao getResourcesEntityDao() {
        return resourcesEntityDao;
    }

    public ResTagEntityDao getResTagEntityDao() {
        return resTagEntityDao;
    }

}
